// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go
//
// Generated by this command:
//
//	mockgen -source settings.go -destination ./mock/settings_mock.go -package mock SettingsDatabase
//

// Package mock is a generated GoMock package.
package mock

import (
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsDatabase is a mock of SettingsDatabase interface.
type MockSettingsDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsDatabaseMockRecorder
}

// MockSettingsDatabaseMockRecorder is the mock recorder for MockSettingsDatabase.
type MockSettingsDatabaseMockRecorder struct {
	mock *MockSettingsDatabase
}

// NewMockSettingsDatabase creates a new mock instance.
func NewMockSettingsDatabase(ctrl *gomock.Controller) *MockSettingsDatabase {
	mock := &MockSettingsDatabase{ctrl: ctrl}
	mock.recorder = &MockSettingsDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsDatabase) EXPECT() *MockSettingsDatabaseMockRecorder {
	return m.recorder
}
